apiVersion: v1
kind: Pod
metadata:
  name: pod-with-limits
spec:
  containers:
    - name: app-container
      image: nginx
      resources:
        limits:
          memory: "512Mi"
          cpu: "500m"
