apiVersion: v1
kind: Pod
metadata:
  name: pod-with-limits
  namespace: secure-namespace                        # Avoid using the default namespace
  annotations:
    container.apparmor.security.beta.kubernetes.io/app-container: runtime/default  # Add AppArmor profile
    seccomp.security.alpha.kubernetes.io/pod: runtime/default                      # Add pod-level seccomp profile
spec:
  serviceAccountName: custom-service-account         # Define service account name
  automountServiceAccountToken: false               # Disable service account token automount
  containers:
    - name: app-container
      image: nginx@sha256:123abc456def789ghi         # Use an image with a digest
      securityContext:
        runAsUser: 1000                             # Run container as a high UID
        runAsNonRoot: true                          # Ensure the container runs as a non-root user
        allowPrivilegeEscalation: false             # Do not allow privilege escalation
        capabilities:
          drop:                                     # Minimize capabilities assigned
            - ALL
        seccompProfile:
          type: RuntimeDefault                      # Set seccomp profile
        readOnlyRootFilesystem: true               # Use a read-only filesystem
      resources:
        requests:
          memory: "128Mi"                           # Define memory requests
          cpu: "250m"
        limits:
          memory: "512Mi"
          cpu: "500m"
      volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx
          readOnly: true                            # Use a read-only filesystem
      livenessProbe:                                # Add liveness probe
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 10
      readinessProbe:                               # Add readiness probe
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 10
  volumes:
    - name: config-volume
      emptyDir: {}
